const EN = {
  dir: 'ltr' as 'ltr' | 'rtl',
  docLabel: 'UPSIDEDOWN RETREAT',
  title: 'Airport Transfer',
  greeting: (name: string) => `Hi ${name},`,
  intro: 'We offer a group transfer to and from the airport. Let us know if you’d like a seat on either ride — takes a minute.',
  reviewNote: 'You already submitted an answer below. Feel free to review and update it.',
  scheduleTitle: 'The fixed schedule',
  arrivalScheduleLabel: 'Arrival transfer — Heraklion Airport → the farm',
  departureScheduleLabel: 'Departure transfer — the farm → Heraklion Airport',
  whatsappNote: 'Exact meeting point will be shared in the WhatsApp group closer to the date.',
  arrivalLabel: 'Pickup from the airport on arrival?',
  departureLabel: 'Drop-off to the airport on departure?',
  yes: 'Yes, count me in',
  no: 'No, I’ll arrange my own',
  luggageLabel: 'Do you have a large suitcase?',
  luggageHint: 'Helps us make sure the van has room for everyone’s bags.',
  luggageYes: 'Yes, a large one',
  luggageNo: 'No, just carry-on / small bag',
  flightLabel: 'Flight number (optional)',
  flightPlaceholder: 'e.g. LY1234',
  submit: 'Submit my answer',
  submitting: 'Submitting...',
  update: 'Update my answer',
  allSet: 'All set!',
  allSetMsg: (name: string) => `Thanks ${name} — we’ve got your transfer details. You can come back and update them any time before the retreat.`,
  invalidLink: 'This link is invalid or has expired.',
  contactUs: 'Contact us at info@upsidedown-retreat.com',
  loading: 'Loading...',
  validationMsg: 'Please answer both pickup and drop-off to continue.',
}

const HE: typeof EN = {
  dir: 'rtl',
  docLabel: 'ריטריט UPSIDEDOWN',
  title: 'הסעה משדה התעופה',
  greeting: (name: string) => `שלום ${name},`,
  intro: 'אנחנו מציעים הסעה קבוצתית משדה התעופה ובחזרה. ספרו לנו אם תרצו מקום באחת הנסיעות או בשתיהן — זה לוקח דקה.',
  reviewNote: 'כבר שלחתם תשובה. אתם מוזמנים לבדוק ולעדכן אותה.',
  scheduleTitle: 'לוח הזמנים הקבוע',
  arrivalScheduleLabel: 'הסעת הגעה — נמל התעופה הרקליון ← החווה',
  departureScheduleLabel: 'הסעת עזיבה — החווה ← נמל התעופה הרקליון',
  whatsappNote: 'המיקום המדויק יישלח בקבוצת הוואטסאפ קרוב יותר לתאריך.',
  arrivalLabel: 'איסוף משדה התעופה בהגעה?',
  departureLabel: 'הורדה לשדה התעופה בעזיבה?',
  yes: 'כן, תספרו עלי',
  no: 'לא, אני אתארגן לבד',
  luggageLabel: 'יש לכם מזוודה גדולה?',
  luggageHint: 'עוזר לנו לוודא שיש מקום ברכב לכל המזוודות.',
  luggageYes: 'כן, מזוודה גדולה',
  luggageNo: 'לא, רק תיק על גב / תיק קטן',
  flightLabel: 'מספר טיסה (לא חובה)',
  flightPlaceholder: 'לדוגמה LY1234',
  submit: 'שליחת התשובה שלי',
  submitting: 'שולח...',
  update: 'עדכון התשובה שלי',
  allSet: 'הכול מוכן!',
  allSetMsg: (name: string) => `תודה ${name} — קיבלנו את פרטי ההסעה שלכם. אפשר לחזור ולעדכן אותם בכל עת לפני הריטריט.`,
  invalidLink: 'הקישור אינו תקף או שפג תוקפו.',
  contactUs: 'צרו קשר בכתובת info@upsidedown-retreat.com',
  loading: 'טוען...',
  validationMsg: 'אנא ענו גם על איסוף וגם על הורדה כדי להמשיך.',
}

export function tx(locale: string) {
  return locale === 'he' ? HE : EN
}
